# Data
data_name: 'yelp'
data_dir: './data/'
train_ratio: 0.1
test_ratio: 0.67
save_dir: './pytorch_modelsl/'

# Model
model: 'PCGNN'
multi_relation: 'GNN'


# Model architecture
emb_size: 64

thres: 0.5

rho: 0.5
# rho:
#   - 0.2
#   - 0.4
#   - 0.6
#   - 0.8

seed: 72

# # Run multiple times with different random seeds
# seed:
#     - 42
#     - 448
#     - 854
#     - 29493
#     - 88867


# hyper-parameters
optimizer: 'adam'
lr: 0.01 
weight_decay: 0.001
batch_size: 512
num_epochs: 150
valid_epochs: 5
alpha: 2
#multi_run: True


# Device
mlp_num_feat: 32
no_cuda: False
cuda_id: '1'
graph_learn: True
graph_metric_type: 'weighted_cosine' # weighted_cosine, kernel, attention, gat_attention, cosine
hidden_size: 25
graph_skip_conn: 0.9 # 0.9, IL: 0.8!
graph_include_self: False
scalable_run: True
graph_hops: 3
graph_learn_hidden_size: 70 # kernel: 100, attention: 70
graph_learn_topk: null # 200
graph_learn_epsilon: 0.5 # weighted_cosine: 0!
graph_learn_num_pers: 4 # weighted_cosine: GL: 4, IGL: 4!
graph_learn_regularization: True
smoothness_ratio: 0.2 # 0.2, IL: 0.2!
degree_ratio: 0 # 0!
sparsity_ratio: 0.1 # 0, IL: 0.1!
num_anchors: 256
eps_adj: 8.5e-5
update_adj_ratio: 0.5